import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

import "./globals.css";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import WhatsAppButton from "@/components/Whatsapp/whatsapp-button";
import Navbar from "../components/Navbar/navbar";
import Header from "../components/Header/header";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ConInversion",
  description: "Generated by create ConInversion",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className}  min-h-screen`}>

            <Navbar />
            <Header />
            <WhatsAppButton />
          {children}</body>
          
    </html>
  );
}
